version: "3"
services:
  eureka-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    restart: always
    networks:
      - backend
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - backend
  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - backend
networks:
  backend:
#--
