version: "3"
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    restart: always
    networks:
      - backend
  user-service:
    build:
      context:
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - backend
networks:
  backend:
